### ISSUE TITLE
你好，请问可不可以详细说一下怎么运行

### ISSUE THREAD

**Issue by Brannua** [weechang/wifi-connector#2]
(搬家了没wifi，唉)

我按步骤来执行的.java文件，设置了-encoding utf-8，不然报错-》错误: 编码 GBK 的不可映射字符 (0x80)，执行文件报错如下，望解答，谢谢你~

C:\Users\Administrator\Desktop\wifi-connector\connector\src\main\java\io\github\weechang\cmd>javac -encoding utf-8 WlanExecute.java
WlanExecute.java:3: 错误: 找不到符号
import io.github.weechang.Connector;
                         ^
  符号:   类 Connector
  位置: 程序包 io.github.weechang
WlanExecute.java:4: 错误: 程序包io.github.weechang.config不存在
import io.github.weechang.config.Command;
                                ^
WlanExecute.java:50: 错误: 找不到符号
    public static List<Ssid> listSsid() {
                       ^
  符号:   类 Ssid
  位置: 类 WlanExecute
WlanExecute.java:51: 错误: 找不到符号
        List<Ssid> ssidList = new ArrayList<Ssid>();
             ^
  符号:   类 Ssid
  位置: 类 WlanExecute
WlanExecute.java:51: 错误: 找不到符号
        List<Ssid> ssidList = new ArrayList<Ssid>();
                                            ^
  符号:   类 Ssid
  位置: 类 WlanExecute
WlanExecute.java:52: 错误: 找不到符号
        String cmd = Command.SHOW_NETWORKS;
                     ^
  符号:   变量 Command
  位置: 类 WlanExecute
WlanExecute.java:66: 错误: 程序包Command不存在
        String cmd = Command.ADD_PROFILE.replace("FILE_NAME", profileName);
                            ^
WlanExecute.java:67: 错误: 找不到符号
        List<String> result = execute(cmd, Connector.PROFILE_TEMP_PATH);
                                           ^
  符号:   变量 Connector
  位置: 类 WlanExecute
WlanExecute.java:83: 错误: 程序包Command不存在
        String cmd = Command.CONNECT.replace("SSID_NAME", ssid);
                            ^
WlanExecute.java:98: 错误: 找不到符号
        String cmd = "ping " + Connector.PING_DOMAIN;
                               ^
  符号:   变量 Connector
  位置: 类 WlanExecute
10 个错误

**Comment by geekyouth** [comment]
代码不全，必要部分自己补充，建议使用 IDEA 运行
